[package]
name = "obs-plugin-follow-active-window"
version = "0.2.0"
edition = "2021"

[dependencies]
obs-wrapper = { version = "0.4.1" }
log = "0.4"
active-win-pos-rs = { version = "0.7.1" }

[lib]
name = "followactivewindow"
crate-type = ["cdylib"]
